/** PDF report generation for a completed analysis (client-side, jsPDF). */
import jsPDF from "jspdf";
import type { AnalysisResult } from "./pipeline";
import { featureMeta } from "./features";
import { fmt } from "./ui";

export function generateReport(a: AnalysisResult) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = M;

  const line = (text: string, size = 10, bold = false, gap = 14) => {
    if (y > H - M) {
      doc.addPage();
      y = M;
    }
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    for (const l of doc.splitTextToSize(text, W - 2 * M) as string[]) {
      if (y > H - M) {
        doc.addPage();
        y = M;
      }
      doc.text(l, M, y);
      y += gap;
    }
  };
  const rule = () => {
    doc.setDrawColor(190);
    doc.line(M, y, W - M, y);
    y += 12;
  };

  line("EEG Early Seizure Risk Assessment — Research Report", 16, true, 22);
  line(
    "EEG Parameter-Based Early Seizure Risk Assessment Using Pattern Comparison and Machine Learning",
    9,
    false,
    12,
  );
  rule();

  line("NOT A MEDICAL DEVICE", 11, true, 14);
  line(
    "This report is generated by a research prototype. Results are algorithmic estimates derived from signal parameters and a statistical model, are not clinically validated, and must not be used for diagnosis, monitoring, treatment or any clinical decision. Always consult a qualified neurologist.",
    9,
    false,
    12,
  );
  if (a.source === "demo") {
    line(
      `SYNTHETIC DEMO DATA — ${a.recordingLabel ?? "generated signal, not a real patient recording"}.`,
      9,
      true,
      14,
    );
  }
  rule();

  line("1. Recording", 12, true);
  line(`File: ${a.fileName}`);
  line(`Analysed at: ${new Date(a.createdAt).toLocaleString()}`);
  line(`Sampling rate: ${a.samplingRate} Hz · Duration: ${a.durationSec.toFixed(1)} s`);
  line(`Channels: ${a.channelNames.join(", ")}`);
  line(`Analysed channel: ${a.analysedChannel}`);
  line(`Analysis window: ${a.windowStart.toFixed(1)}–${a.windowEnd.toFixed(1)} s`);
  line(`Signal quality: ${a.qualityStatus}`);
  y += 6;

  line("2. Preprocessing", 12, true);
  a.preprocessSteps.forEach((s) => line(`• ${s.name}: ${s.detail}`, 9, false, 12));
  y += 6;

  line("3. Risk assessment", 12, true);
  line(`Classification: ${a.risk.classification}`, 11, true);
  line(`Risk score: ${a.risk.riskScore.toFixed(1)} / 100`);
  line(`Model confidence: ${a.risk.confidence.toFixed(1)}%`);
  line(
    `Class probabilities — interictal ${(a.risk.probs.interictal * 100).toFixed(1)}%, preictal ${(a.risk.probs.preictal * 100).toFixed(1)}%, ictal ${(a.risk.probs.ictal * 100).toFixed(1)}%`,
  );
  line(
    `Pattern similarity — interictal ${a.risk.similarity.interictal.toFixed(1)}%, preictal ${a.risk.similarity.preictal.toFixed(1)}%, ictal ${a.risk.similarity.ictal.toFixed(1)}%`,
  );
  if (a.risk.earlyWarning) line("EARLY WARNING FLAG RAISED (research indicator only).", 10, true);
  y += 6;

  line("4. Model", 12, true);
  line(`${a.modelName}`);
  line(`Algorithm: ${a.modelAlgorithm}`);
  line(`Reference dataset origin: ${a.modelDatasetOrigin} · Features used: ${a.featureCount}`);
  y += 6;

  line("5. Top contributing parameters (explainability)", 12, true);
  a.contributions.slice(0, 10).forEach((c) => {
    const m = featureMeta(c.key);
    line(
      `• ${m.label}: ${fmt(a.features[c.key])} ${m.unit} — contribution ${c.contribution.toFixed(1)}% (z = ${c.z.toFixed(2)}, ${c.direction})`,
      9,
      false,
      12,
    );
  });
  y += 6;

  line("6. Band powers", 12, true);
  a.bandPowers.forEach((b) =>
    line(`• ${b.band}: ${fmt(b.absolute)} µV² absolute · ${(b.relative * 100).toFixed(1)}% relative`, 9, false, 12),
  );
  y += 6;

  line("7. Extracted parameters", 12, true);
  Object.keys(a.features).forEach((k) => {
    const m = featureMeta(k);
    line(`• ${m.label}: ${fmt(a.features[k])} ${m.unit}`, 8, false, 11);
  });

  doc.addPage();
  y = M;
  line("8. Reference comparison (vs. predicted class distribution)", 12, true);
  const comp = a.comparisons[a.risk.predictedClass] ?? [];
  comp.forEach((c) => {
    const m = featureMeta(c.key);
    line(
      `• ${m.label}: ${fmt(c.value)} | ref mean ${fmt(c.reference.mean)} ± ${fmt(c.reference.sd)} | z = ${c.z.toFixed(2)} | ${c.status}`,
      8,
      false,
      11,
    );
  });

  y += 10;
  rule();
  line(
    "Generated locally in the browser. No patient data was transmitted. Report ID: " + a.id,
    8,
    false,
    11,
  );

  doc.save(`eeg-risk-report-${a.id}.pdf`);
}
